CREATE DATABASE QLNK
USE QLNK

CREATE TABLE ACCOUNT
(
	USERNAME VARCHAR(100) NOT NULL,
	GMAIL NCHAR(100) NOT NULL,
	PASS CHAR(50) NOT NULL,
	CONFIRM CHAR(50) NOT NULL,
	CONSTRAINT PK_USER PRIMARY KEY (USERNAME)
)

SELECT * FROM ACCOUNT


CREATE TABLE HOKHAU (
	MAHOKHAU INT NOT NULL,
	HOTENCHUHO NVARCHAR(50) NOT NULL,
	NGAYSINH VARCHAR(50) NOT NULL,
	GIOITINH INT NOT NULL,
	DANTOC NVARCHAR(50) NOT NULL,
	QUOCTICH NVARCHAR(50) NOT NULL,
	DIACHI NVARCHAR(50) NOT NULL,
	NGAYDANGKY VARCHAR(50) NOT NULL,
	ANH IMAGE NULL,
	CONSTRAINT PK_MAHOKHAU PRIMARY KEY (MAHOKHAU)
)

SELECT * FROM HOKHAU


CREATE TABLE NHANKHAU (
	MAKHAISINH INT NOT NULL,
	HOTEN NVARCHAR(50) NOT NULL,
	NGAYSINH VARCHAR(50) NOT NULL,
	NOISINH NVARCHAR(50) NOT NULL,
	QUEQUAN NVARCHAR(50) NOT NULL,
	NOIOHIENTAI NVARCHAR(50) NOT NULL,
	GIOITINH INT NOT NULL,
	CMND INT NOT NULL,
	NGAYCAP VARCHAR(50) NOT NULL,
	NOICAPCMND NVARCHAR(50) NOT NULL,
	DANTOC NVARCHAR(50) NOT NULL,
	TONGIAO NVARCHAR(50) NULL,
	QUANHEVOICHUHO NVARCHAR(50) NOT NULL,
	ANH IMAGE NULL,
	MAHOKHAU INT NOT NULL,
	CONSTRAINT PK_MAKHAISINH PRIMARY KEY (MAKHAISINH),
	CONSTRAINT FK_NHANKHAU_MAHOKHAU FOREIGN KEY (MAHOKHAU) REFERENCES HOKHAU(MAHOKHAU)
)



SELECT * FROM NHANKHAU

ALTER TABLE NHANKHAU
DROP CONSTRAINT FK_NHANKHAU_MAHOKHAU

ALTER TABLE NHANKHAU
ADD CONSTRAINT FK_NHANKHAU_MAHOKHAU
				FOREIGN KEY(MAHOKHAU)
				REFERENCES HOKHAU
				ON DELETE CASCADE
				ON UPDATE CASCADE

ALTER TABLE NHANKHAU
ADD CONSTRAINT UNI_CMND UNIQUE(CMND)

ALTER TABLE NHANKHAU
ADD CONSTRAINT CHECK_NGAY
	CHECK(convert(varchar, NGAYCAP, 103) > convert(varchar, NGAYSINH, 103))

ALTER TABLE HOKHAU
ADD CONSTRAINT CHECK_NGAY_HOKHAU
	CHECK(convert(varchar, NGAYDANGKY, 103) > convert(varchar, NGAYSINH, 103))
ALTER TABLE HOKHAU
DROP CONSTRAINT CHECK_NGAY_HOKHAU